#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Lint backend
echo "Linting backend..."
npm run lint --prefix backend || {
  echo "Backend linting failed!"
  exit 1
}

# Lint frontend
echo "Linting frontend..."
npm run lint --prefix frontend || {
  echo "Frontend linting failed!"
  exit 1
}

# Section for git-secrets
GIT_SECRETS_PATH="/usr/local/bin/git-secrets"  # Adjust this path if necessary
# Section for git-secrets
if [ ! -x "$GIT_SECRETS_PATH" ]
# if ! command -v git-secrets &> /dev/null
then
   echo "git-secrets is not installed. Please run 'brew install git-secrets' or visit https://github.com/awslabs/git-secrets#installing-git-secrets"
   exit 1
fi 

# Initialise git-secrets configuration
git-secrets --register-aws > /dev/null

echo "Running git-secrets..."
# Scans all files that are about to be committed.
git-secrets --scan -r

