#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Lint backend
echo "Linting backend..."
npm run lint --prefix backend || {
  echo "Backend linting failed!"
  exit 1
}

# Lint frontend
echo "Linting frontend..."
npm run lint --prefix frontend || {
  echo "Frontend linting failed!"
  exit 1
}

# Check for secrets
echo "Checking for secrets..."
git-secrets --scan ./ || {
  echo "Secret detection failed!"
  exit 1
}
